## Numpy

In [1]:
import numpy as np

In [3]:
# 1D array
arr1 = np.array([1,2,3,4,5])
arr1
print(type(arr1))
print(arr1.shape)

<class 'numpy.ndarray'>
(5,)


In [4]:
arr2 = arr1
arr2.reshape((1,5))  # 1 row and 5 cols

array([[1, 2, 3, 4, 5]])

In [5]:
# 2D array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [6]:
a=np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [7]:
a.dtype

dtype('int64')

In [8]:
a.reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
# Identity Matrix
b=np.eye(3, dtype=int) # by default float dtype
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [11]:
b.itemsize

8

## Numpy Vectorize Operations

In [13]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise Addition
print("Addition: ", arr1 + arr2)

# Element wise Substraction
print("Substraction: ", arr1 - arr2)

# Element wise Multiplication
print("Multiplication: ", arr1 * arr2)

# Element wise Division
print("Division: ", arr1 / arr2)

Addition:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [18]:
## Universal function
arr = np.array([2,3,4,5,6])

# square root
print(np.sqrt(arr))
# exponential
print(np.exp(arr))
# log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [43]:
# array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [44]:
arr[0][0]

np.int64(1)

In [45]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [46]:
# modify arr
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [47]:
arr[1:,2:] = 99
print(arr)

[[100   2   3   4]
 [  5   6  99  99]
 [  9  10  99  99]]


## Statistical Operations

In [52]:
data = np.arange(1,11)

# Mean
mean = np.mean(data)
print("Mean: ",mean)

# Median
median = np.median(data)
print("Median: ", median)

# Std Deviation
std_dev = np.std(data)
print("Std Deviation: ",std_dev)

# Variance
variance = np.var(data)
print("Variance: ", variance)

Mean:  5.5
Median:  5.5
Std Deviation:  2.8722813232690143
Variance:  8.25


In [53]:
# Logical Operations

data >5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [54]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [55]:
data[(data>=5) & (data <=8)]

array([5, 6, 7, 8])