In [2]:
import torch

In [3]:
a = torch.tensor([1, 2, 3])
print(a)

tensor([1, 2, 3])


In [4]:
b = torch.tensor([[1, 2, 3], [4, 5, 6],[7, 8, 9],[10,11,12]])
b

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [5]:
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [6]:
print(b.shape[0])

4


In [7]:
c = torch.FloatTensor([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
print(c)
print(c.dtype)

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.]])
torch.float32


In [8]:
d = torch.DoubleTensor([[1, 2, 3, 4], [2, 3, 4, 5]])
print(d)
print(d.dtype)

tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.]], dtype=torch.float64)
torch.float64


In [9]:
print(c.mean())

tensor(3.)


In [10]:
print(d.mean())

tensor(3., dtype=torch.float64)


In [11]:
print(c.std())

tensor(1.2247)


In [12]:
print(d.std())

tensor(1.3093, dtype=torch.float64)


In [13]:
# view
print("Original b")
print(b)
print(b.view(-1,1))
print(b.view(12))
print(b.view(1,-1))
print(b.view(3,-1))
print(b.view(2,-1))

# create a 3D tensor
three_dim = torch.randn(1, 3, 4)
print(three_dim)


Original b
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])
tensor([[[ 1.2322,  0.9413,  0.2737,  0.9133],
         [-2.3500, -0.2248, -0.9693,  0.4929],
         [ 0.0276, -0.8940,  0.1974,  0.1904]]])


In [14]:
r = torch.rand(4, 4)
r

tensor([[0.0285, 0.7438, 0.5328, 0.4433],
        [0.5978, 0.2232, 0.4640, 0.5759],
        [0.9238, 0.6861, 0.1516, 0.7976],
        [0.4771, 0.5077, 0.8488, 0.4043]])

In [15]:
r2 = torch.randn(4, 4)
print(r2)
print(r2.dtype)

tensor([[ 0.7287,  0.9048, -0.9349, -0.3644],
        [-1.0312,  1.4359,  0.0578,  0.4645],
        [ 0.8928, -0.8499, -0.7346,  2.4115],
        [ 2.7974,  0.4689,  0.5316, -0.0751]])
torch.float32


In [16]:
import numpy as np

In [17]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
c = np.array([1, 2, 3, 4])
print(c)

print(a.dtype)
print(b.dtype)
print(c.dtype)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
[1 2 3 4]
torch.float32
float32
int64


In [18]:
torch.cuda.is_available()

False