In [2]:
from sentence_transformers import SentenceTransformer

# Load a pre-trained sentence embedding model
model_name = 'all-MiniLM-L6-v2'
model = SentenceTransformer(model_name)

print(f"Model '{model_name}' loaded successfully.")
# Output: Model 'all-MiniLM-L6-v2' loaded successfully.

c:\Users\admin\Desktop\Projects\AI_ML_DATASCIENCE\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\admin\Desktop\Projects\AI_ML_DATASCIENCE\.venv\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\admin\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to 

Model 'all-MiniLM-L6-v2' loaded successfully.


In [3]:
import numpy as np

sentences = [
    "The delivery arrived on time.",
    "My package was delivered promptly.",
    "Vector databases store numerical representations.",
    "How can I optimize database queries?",
    "The weather today is sunny and warm."
]

# Generate embeddings for the sentences
embeddings = model.encode(sentences)

# Check the dimensions of the embeddings
print(f"Shape of embeddings matrix: {embeddings.shape}")
# Output: Shape of embeddings matrix: (5, 384)

# Display the first few dimensions of the first embedding
print(f"First 5 dimensions of the first sentence embedding:\n{embeddings[0, :5]}")
# Output: First 5 dimensions of the first sentence embedding:
# [-0.0568201  -0.01949895  0.00780028  0.03499191 -0.0031617 ]

Shape of embeddings matrix: (5, 384)
First 5 dimensions of the first sentence embedding:
[-0.05027558  0.04267898 -0.01072991  0.04200416  0.01438534]


In [4]:
from scipy.spatial.distance import cosine

# Calculate pairwise cosine similarity
num_sentences = len(sentences)
similarity_matrix = np.zeros((num_sentences, num_sentences))

for i in range(num_sentences):
    for j in range(num_sentences):
        # Cosine distance = 1 - cosine similarity
        similarity = 1 - cosine(embeddings[i], embeddings[j])
        similarity_matrix[i, j] = similarity

# Print the similarity matrix (rounded for readability)
print("Pairwise Cosine Similarity Matrix:")
print(np.round(similarity_matrix, 2))

Pairwise Cosine Similarity Matrix:
[[ 1.    0.7   0.    0.03  0.15]
 [ 0.7   1.    0.03  0.09  0.12]
 [ 0.    0.03  1.    0.27 -0.01]
 [ 0.03  0.09  0.27  1.    0.04]
 [ 0.15  0.12 -0.01  0.04  1.  ]]


In [9]:
from sklearn.decomposition import PCA
import plotly.graph_objects as go

# Reduce dimensions to 2D using PCA
pca = PCA(n_components=2)
embeddings_2d = pca.fit_transform(embeddings)

# Create a scatter plot (using pre-calculated example coordinates for consistency)
# Replace these coordinates with the actual output of your PCA transformation
# if you run the code yourself.
example_coords = {
    "x": [-0.15, -0.18, 0.10, 0.25, -0.02],
    "y": [0.08, 0.10, -0.05, -0.12, 0.01]
}

fig = go.Figure(data=go.Scatter(
    # x=embeddings_2d[:, 0], # Use actual PCA output
    # y=embeddings_2d[:, 1], # Use actual PCA output
    x=example_coords["x"], # Using example values
    y=example_coords["y"], # Using example values
    mode='markers+text',
    marker=dict(
        size=10,
        color=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd'], # Example colors
        opacity=0.8
    ),
    text=[f"'{s[:20]}...'" for s in sentences], # Display shortened text labels
    textposition='top center'
))

fig.update_layout(
    title='2D PCA Projection of Sentence Embeddings',
    xaxis_title='Principal Component 1',
    yaxis_title='Principal Component 2',
    width=700,
    height=500,
    showlegend=False
)

# To display the plot (e.g., in a Jupyter Notebook or save to HTML)
fig.show()

# # Or generate the JSON for web embedding
# chart_json = fig.to_json()
# print("\nPlotly JSON for embedding visualization:")
# # Ensure the JSON output is on a single line for the ```plotly block
# print(chart_json.replace("\n", "").replace(" ", ""))

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed